name: kinderseg
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.8
  - pip=23.2
  - cycler=0.11.0
  - fonttools=4.31.2
  - h5py=3.6.0
  - imageio=2.16.1
  - kiwisolver=1.4.2
  - matplotlib=3.5.1
  - networkx=2.7.1
  - nibabel=3.2.2
  - pandas=2.0.3
  - fslpy=3.8.0
  - numpy=1.22.3
  - packaging=21.3
  - pillow=9.0.1
  - plotly=5.6.0
  - pyparsing=3.0.7
  - python-dateutil=2.8.2
  - pywavelets=1.3.0
  - pyyaml=6.0
  - scikit-image=0.19.2
  - scipy=1.8.0
  - simpleitk=2.1.1
  - six=1.15.0
  - tenacity=8.0.1
  - tifffile=2022.3.25
  - typing-extensions=4.1.1
  - lapy

