#!/bin/bash
#
#SBATCH --job-name=KinderSegFreeSurfer
#SBATCH --output=sbatch_KinderSeg_FreeSurfer_LOG.txt
#
#SBATCH --ntasks=16
#SBATCH --nodes=1
#SBATCH --time=##############################
#SBATCH --mem-per-cpu=4G
#SBATCH --partition=compute
#SBATCH --mail-user=###################


bash run_freesurfer

