#!/bin/bash

## Install enviroment:
# conda create -n fastsurfer
# conda activate fastsurfer
# conda install pytorch torchvision cudatoolkit=11 cudnn -c pytorch
# conda install -c conda-forge numpy scipy scikit-image cycler decorator h5py imageio kiwisolver matplotlib nibabel Pillow pyparsing PyWavelets scikit-image six

#Fastsurfer needs freesurfer 6
export FREESURFER_HOME="/usr/local/freesurfer_6"
#/fast/users/dellorca_c/work/freesurfer-6
source $FREESURFER_HOME/SetUpFreeSurfer.sh

fastsurfer_dir="/home/ibrazug/Dokumente/FastSurfer" #Dir with Fastsurfer cloned from Github
src_dir="/run/user/1016/gvfs/smb-share:server=charite.de,share=centren/AG/AG-Neurorad/Daten/Andrea/data/kinderseg_v2/0523_M" # Dir with subjects
dest_dir="/home/ibrazug/Dokumente/KindersegV2/Ibra/Martin_Fastsurfer_Seg"
mkdir -p $dest_dir

cd $src_dir
subs=($(ls -1d sub-*))
echo ${subs[@]}
cd $fastsurfer_dir

for sub in ${subs[@]}
do
  echo $sub
  if [ ! -e "${dest_dir}/${sub}/mri/aparc.DKTatlas+aseg.deep.mgz" ]
  then
    t1=`ls ${src_dir}/${sub}/*.nii.gz`
    ./run_fastsurfer.sh --seg_only \
                        --vol_segstats \
                        --parallel --threads 20 \
                        --sd $dest_dir \
                        --sid $sub \
                        --t1 "$t1" \


  else
    echo "$sub seg found! skipping"
  fi
done
