#!/bin/bash

## Install enviroment:
# conda create -n fastsurfer
# conda activate fastsurfer
# conda install pytorch torchvision cudatoolkit=11 cudnn -c pytorch
# conda install -c conda-forge numpy scipy scikit-image cycler decorator h5py imageio kiwisolver matplotlib nibabel Pillow pyparsing PyWavelets scikit-image six

#Fastsurfer needs freesurfer 6
export FREESURFER_HOME="/usr/local/freesurfer_6"
#/fast/users/dellorca_c/work/freesurfer-6
source $FREESURFER_HOME/SetUpFreeSurfer.sh

fastsurfer_dir="" #Dir with Fastsurfer cloned from Github
src_dir="" # Dir with subjects
dest_dir=""
mkdir -p $dest_dir

cd $src_dir
subs=($(ls -1d sub-*))
echo ${subs[@]}
cd $fastsurfer_dir

for sub in ${subs[@]}
do
  echo $sub
  if [ ! -e "${dest_dir}/${sub}/mri/aparc.DKTatlas+aseg.deep.mgz" ]
  then
    t1=`ls ${src_dir}/*.nii.gz`
    ./run_fastsurfer.sh --seg_only \
                        --sd $dest_dir \
                        --sid $sub \
                        --t1 $t1 \
                        --parallel --threads 20 \
                        --vol_segstats
  else
    echo "$sub seg found! skipping"
  fi
done
