#!/bin/bash
#
#SBATCH --job-name=KinderSegV2FreeSurfer
#SBATCH --output=sbatch_KinderSeg_FreeSurfer_LOG.txt
#
#SBATCH --ntasks=16
#SBATCH --nodes=1
#SBATCH --time=00-12:00:00
#SBATCH --mem-per-cpu=4G
#SBATCH --partition=compute
#SBATCH --mail-user=andrea.dellorco@charite.de


bash run_freesurfer

